app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('client', 'ClientController');
Route::resource('facture', 'FactureController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'nom', 'telephone', 'email', 'created_at', 'updated_at'
    ];

    public function factures()
    {
        return $this->hasMany(Facture::class);
    }
}

app/Facture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Facture extends Model
{
    protected $fillable = [
        'client_id', 'nom', 'created_at', 'updated_at'
    ];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\ClientRepository;

use App\Http\Requests;

class ClientController extends Controller
{
    private $clientRepository;

    private $numberPerPage = 5;

    public function __construct(ClientRepository $clientRepository)
    {
        $this->clientRepository = $clientRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = $this->clientRepository->getPaginate($this->numberPerPage);
        $links = $clients->render();

        return view('client/index', compact('clients', 'links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Requests\ClientRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\ClientRequest $request)
    {
        $client = $this->clientRepository->store($request->all());

        return redirect()
            ->route('client.index')
            ->with('success','Le client '.$client->nom.' bien enregistré');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = $this->clientRepository->getById($id);

        return view('client/show', compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = $this->clientRepository->getById($id);

        return view('client/edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Requests\ClientRequest $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\ClientRequest $request, $id)
    {
        $this->clientRepository->update($id, $request->all());

        return redirect()->route('client.index')->with('success', 'Le client '.$request->input('nom').' a bien été modifié.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->clientRepository->destroy($id);

        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FactureController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests;
use App\Repositories\ClientRepository;
use App\Repositories\FactureRepository;

class FactureController extends Controller
{
    private $factureRepository;

    private $numberPerPage = 5;

    public function __construct(FactureRepository $factureRepository)
    {
        $this->factureRepository = $factureRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $factures = $this->factureRepository->getPaginate($this->numberPerPage);
        $links = $factures->render();

        return view('facture/index', compact('factures', 'links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param ClientRepository $clientRepository
     * @return \Illuminate\Http\Response
     */
    public function create(ClientRepository $clientRepository)
    {
        $clients = $clientRepository->getAll();

        return view('facture/create', compact('clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Requests\FactureRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\FactureRequest $request)
    {
        $facture = $this->factureRepository->store($request->all());

        return redirect()
            ->route('facture.index')
            ->with('success','La facture '.$facture->nom.' bien enregistrée');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $facture = $this->factureRepository->getById($id);

        return view('facture/show', compact('facture'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ClientRepository $clientRepository
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(ClientRepository $clientRepository, $id)
    {
        $facture = $this->factureRepository->getById($id);
        $clients = $clientRepository->getAll();

        return view('facture/edit', compact('facture', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Requests\FactureRequest $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\FactureRequest $request, $id)
    {
        $this->factureRepository->update($id, $request->all());

        return redirect()->route('facture.index')->with('success', 'La facture '.$request->input('nom').' a bien été modifiée.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->factureRepository->destroy($id);

        return redirect()->back();
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Test technique -@yield('title')</title>

    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">

    <script src="{{ asset('assets/js/jquery.min.js') }}"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a href="{{ route('client.index') }}">Clients</a>
                    </li>
                    <li>
                        <a href="{{ route('facture.index') }}">Factures</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
        @yield('content')
    </div>

<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
</body>
</html>

resources/views/client/create.blade.php
@extends('base')

@section('title')
    Client
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Création d'un client</h3>
            </div>
            <div class="panel-body">
                <div class="col-xs-12">
                    {!! Form::open(['route'=>'client.store', 'class'=>'form-horizontal panel']) !!}
                    <div class="form-group {!! $errors->has('nom') ? 'has-error' : '' !!}">
                        {!! $errors->first('nom', '<small class="help-block">:message<small/>') !!}
                        {!! Form::text('nom', null, ['placeholder'=>'Nom', 'class'=>'form-control']) !!}
                    </div>
                    <div class="form-group {!! $errors->has('telephone') ? 'has-error' : '' !!}">
                        {!! $errors->first('telephone', '<small class="help-block">:message<small/>') !!}
                        {!! Form::text('telephone', null, ['placeholder'=>'Telephone', 'class'=>'form-control']) !!}
                    </div>
                    <div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
                        {!! $errors->first('email', '<small class="help-block">:message<small/>') !!}
                        {!! Form::email('email', null, ['placeholder'=>'Email', 'class'=>'form-control']) !!}
                    </div>
                    {!! Form::submit('Envoyer', ['class'=>'btn btn-primary pull-right']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        <a href="javascript:history.back()" class="btn btn-primary">< Retour</a>
    </div>
@endsection

resources/views/client/edit.blade.php
@extends('base')

@section('title')
    Client
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Modification d'un client</h3>
            </div>
            <div class="panel-body">
            <div class="col-xs-12">
                {!! Form::model($client, ['route'=>['client.update', $client->id], 'method'=>'put', 'class'=>'form-horizontal panel']) !!}
                <div class="form-group {!! $errors->has('nom') ? 'has-error' : '' !!}">
                    {!! $errors->first('nom', '<small class="help-block">:message<small/>') !!}
                    {!! Form::text('nom', null, ['placeholder'=>'Nom', 'class'=>'form-control']) !!}
                </div>
                <div class="form-group {!! $errors->has('telephone') ? 'has-error' : '' !!}">
                    {!! $errors->first('telephone', '<small class="help-block">:message<small/>') !!}
                    {!! Form::text('telephone', null, ['placeholder'=>'Telephone', 'class'=>'form-control']) !!}
                </div>
                <div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
                    {!! $errors->first('email', '<small class="help-block">:message<small/>') !!}
                    {!! Form::email('email', null, ['placeholder'=>'Email', 'class'=>'form-control']) !!}
                </div>
                {!! Form::submit('Envoyer', ['class'=>'btn btn-primary pull-right']) !!}
                {!! Form::close() !!}
            </div>
            </div>
        </div>
        <a href="javascript:history.back()" class="btn btn-primary">< Retour</a>
    </div>
@endsection

resources/views/client/index.blade.php
@extends('base')

@section('title')
    Clients
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-1 col-sm-10">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Liste des clients</h3>
            </div>
            <div class="panel-body table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th>Téléphone</th>
                        <th>Email</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($clients as $client)
                        <tr>
                            <td>{!! $client->id !!}</td>
                            <td>{!! $client->nom !!}</td>
                            <td>{!! $client->telephone !!}</td>
                            <td class="text-primary">{!! $client->email !!}</td>
                            <td><a href="{{ route('client.show', ['id'=>$client->id]) }}" class="btn btn-success btn-block">Voir</a></td>
                            <td><a href="{{ route('client.edit', ['id'=>$client->id]) }}" class="btn btn-warning btn-block">Modifier</a></td>
                            <td>
                                {!! Form::open(['method'=>'DELETE', 'route'=>['client.destroy', $client->id]]) !!}
                                {!! Form::submit('Supprimer', ['class'=>'btn btn-danger btn-block']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <td><a href="{{ route('client.create') }}" class="btn btn-info pull-right">Ajouter un client</a></td>
        {!! $links !!}
    </div>
@endsection

resources/views/client/show.blade.php
@extends('base')

@section('title')
    Client
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Fiche client</h3>
            </div>
            <div class="panel-body">
                <p>Nom : {{ $client->nom }}</p>
                <p>Telephone : {{ $client->telephone }}</p>
                <p>Email : {{ $client->email }}</p>
                <p>Créé le : {{ $client->created_at }}</p>
                <p>Modifié le : {{ $client->updated_at }}</p>
            </div>
        </div>
        <a href="javascript:history.back()" class="btn btn-primary">< Retour</a>
    </div>
@endsection

resources/views/facture/create.blade.php
@extends('base')

@section('title')
    Client
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Création d'une facture</h3>
            </div>
            <div class="panel-body">
                <div class="col-xs-12">
                    {!! Form::open(['route'=>'facture.store', 'class'=>'form-horizontal panel']) !!}
                    <div class="form-group {!! $errors->has('client') ? 'has-error' : '' !!}">
                        <select name="client_id" id="client_id" class="form-control">
                            @foreach($clients as $client)
                                <option value="{{ $client->id }}">{{ $client->nom }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group {!! $errors->has('nom') ? 'has-error' : '' !!}">
                        {!! $errors->first('nom', '<small class="help-block">:message<small/>') !!}
                        {!! Form::text('nom', null, ['placeholder'=>'Nom', 'class'=>'form-control']) !!}
                    </div>
                    {!! Form::submit('Envoyer', ['class'=>'btn btn-primary pull-right']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        <a href="javascript:history.back()" class="btn btn-primary">< Retour</a>
    </div>
@endsection

resources/views/facture/edit.blade.php
@extends('base')

@section('title')
    Client
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Modification d'une facture</h3>
            </div>
            <div class="panel-body">
            <div class="col-xs-12">
                {!! Form::model($facture, ['route'=>['facture.update', $facture->id], 'method'=>'put', 'class'=>'form-horizontal panel']) !!}
                <div class="form-group {!! $errors->has('client') ? 'has-error' : '' !!}">
                    <select name="client_id" id="client_id" class="form-control">
                        @foreach($clients as $client)
                            <option value="{{ $client->id }}">{{ $client->nom }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group {!! $errors->has('nom') ? 'has-error' : '' !!}">
                    {!! $errors->first('nom', '<small class="help-block">:message<small/>') !!}
                    {!! Form::text('nom', null, ['placeholder'=>'Nom', 'class'=>'form-control']) !!}
                </div>
                {!! Form::submit('Envoyer', ['class'=>'btn btn-primary pull-right']) !!}
                {!! Form::close() !!}
            </div>
            </div>
        </div>
        <a href="javascript:history.back()" class="btn btn-primary">< Retour</a>
    </div>
    <script>
        $('#client_id').val({{ $facture->client->id }});
    </script>
@endsection

resources/views/facture/index.blade.php
@extends('base')

@section('title')
    Factures
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-2 col-sm-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Liste des factures</h3>
            </div>
            <div class="panel-body table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($factures as $facture)
                        <tr>
                            <td>{!! $facture->id !!}</td>
                            <td>{!! $facture->nom !!}</td>
                            <td><a href="{{ route('facture.show', ['id'=>$facture->id]) }}" class="btn btn-success btn-block">Voir</a></td>
                            <td><a href="{{ route('facture.edit', ['id'=>$facture->id]) }}" class="btn btn-warning btn-block">Modifier</a></td>
                            <td>
                                {!! Form::open(['method'=>'DELETE', 'route'=>['facture.destroy', $facture->id]]) !!}
                                {!! Form::submit('Supprimer', ['class'=>'btn btn-danger btn-block']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <td><a href="{{ route('facture.create') }}" class="btn btn-info pull-right">Ajouter un facture</a></td>
        {!! $links !!}
    </div>
@endsection

resources/views/facture/show.blade.php
@extends('base')

@section('title')
    Facture
@endsection

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Fiche facture</h3>
            </div>
            <div class="panel-body">
                <p>Nom : {{ $facture->nom }}</p>
                <p>Client : {{ $facture->client->nom }}</p>
                <p>Créé le : {{ $facture->created_at }}</p>
                <p>Modifié le : {{ $facture->updated_at }}</p>
            </div>
        </div>
        <a href="javascript:history.back()" class="btn btn-primary">< Retour</a>
    </div>
@endsection